### ISSUE TITLE
zlib include files are now in cocos2d-x/external and cocos2d-x-3rd-party-libs-bin

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x-3rd-party-libs-bin#120]
A newer version of zlib include files are in cocos2d-x/external/zlib/include. They also are part of this repo. When the user uses download-deps the zlib include files in the cocos2d-x/external repo are overwritten. This causes git to think the files have been changed.

The zlib include files should only be in one repo not both.

**Comment by minggo** [comment]
It is fixed.
