### ISSUE TITLE
Missing xxtea library

### ISSUE THREAD

**Issue by rav3r** [cocos2d/cocos2d-x-3rd-party-libs-bin#14]
I think it is required for lua in cocos2d-x 3.2.

**Comment by minggo** [comment]
It is used in source code in cocos2d-x https://github.com/cocos2d/cocos2d-x/tree/v3/external. Because it only has two files, so there is not need to build it for all platforms.

**Comment by rav3r** [comment]
Thanks for explanation. XXTEA is missing in cocos2d-x-3.2.zip package, so i think that it should be in deps.

**Comment by minggo** [comment]
I upzipped cocos2d-x-3.2.zip.
XXTEA is in external/xxtea.

**Comment by rav3r** [comment]
Sorry, my bad - everything is ok.
