### ISSUE TITLE
rapidjson problem

### ISSUE THREAD

**Issue by rny** [cocos2d/cocos2d-x-3rd-party-libs-bin#18]
1. the rapidjosn included is quite old, the newest is https://github.com/miloyip/rapidjson
2. the include path "json" need to be changed to "rapidjson" same as the library.
3. different version of rapidjson in the code can cause runtime-problem in XCODE,(that is why i have to delete the cocos2d-x rapidjson and using only the newest from github)

**Comment by zilongshanren** [comment]
Already upgrade in v3.7. https://github.com/cocos2d/cocos2d-x/issues/11474
