### ISSUE TITLE
希望添加 android 64位.so库

### ISSUE THREAD

**Issue by baibai2013** [cocos2d/cocos2d-x-3rd-party-libs-bin#227]
希望添加 android 64位.so库：arm64-v8a,x86_64, mips64；

**Comment by imsjrhowa** [comment]
https://github.com/inmotionsoftware/cocos2d-x-3rd-party-libs-bin

added x86_64 for android.

**Comment by minggo** [comment]
arm64-v8a is already supported, and there is no plan for x86_64 and mips64
