### ISSUE TITLE
Missing the file lua51-2015.lib and lua51-2015.dll

### ISSUE THREAD

**Issue by wzsg** [cocos2d/cocos2d-x-3rd-party-libs-bin#264]
D:\cocos2d-x-3.14\cocos2d-x-3.14\cocos\scripting\lua-bindings\manual\CCLuaEngine.cpp

#if _MSC_VER > 1800
#pragma comment(lib,"lua51-2015.lib")
#else
#pragma comment(lib,"lua51.lib")
#endif

LINK : fatal error LNK1104:  cannot open file “lua51-2015.lib”

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17146.
