### ISSUE TITLE
Can provide some of the code I winc win32 environment

### ISSUE THREAD

**Issue by coretimes** [cocos2d/cocos2d-x-3rd-party-libs-bin#281]
Can provide the third of the code I compile it win32 environment? Because the project needs I have to compile their own third line, but the allocation of this tripod library environment is too much trouble, can provide a method description or the environment? Grateful!
能提供一下3rd的代码我自己编译吗win32环境?因为项目需求我要自己编译3rd才行，但是配置这个三方库环境太麻烦了，能提供个方法说明或者环境吗？感激不尽！
@zilongshanren @ricardoquesada @elnormous @dumganhar @minggo @xiaofeng11 @stammen @steerlink @martell @stevetranby @super626 @hulefei @fusijie @YamakiHirokazuXX @Watson1978

**Comment by minggo** [comment]
You should access the library's home page, it has the readme to guide you how to compile it.

**Comment by coretimes** [comment]
@minggo Sorry, I downloaded the code from the home page is some links 3rd-libs-src inside the library is not fully compiled out of the basic run up

**Comment by minggo** [comment]
Sorry, what did you mean?

**Comment by coretimes** [comment]
@minggo I have not found in your home how to compile win32 library, and is so much library
Compiler win32 library can support windows xp?

**Comment by minggo** [comment]
I mean the home page is the library's home page. For example, if you want to compile png, you have to refer to http://www.libpng.org/pub/png/ and take a look of its documentation about how to compile.

**Comment by coretimes** [comment]
@minggo  
Oh I understand what you mean, I can only according to the needs of the library to the various open source library to download and then compile their own! So good trouble ah I may need more than a week to configure, can provide the latest compilation of your win32 environment, grateful

**Comment by minggo** [comment]
We don't have the environment. We do it like that.

**Comment by coretimes** [comment]
@minggo Thank you very much.
