### ISSUE TITLE
Warning when building for iOS

### ISSUE THREAD

**Issue by pyrosphere** [cocos2d/cocos2d-x-3rd-party-libs-bin#35]
Hello, when building my cocos2d-x game project for iOS I get the following warning:

```
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in _jinit_arith_decoder from /Users/user/Library/Developer/Xcode/DerivedData/Project/Build/Products/Debug-iphoneos/libcocos2dx iOS.a(jdarith.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
```

From the _jinit_arith_decoder and jdarith.o in the warning I'm deducing it originates from libjpeg (hence posting this issue in this repository). Also this error only occurs when building for a device and not the simulator, so maybe not all slices of libjpeg cause this.

I'm not really sure what is happening but it might be important - the app no longer builds as PIE which Apple doesn't like according to their documentation: https://developer.apple.com/library/ios/qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354

**Comment by pyrosphere** [comment]
I replaced jpeg/prebuilt/ios/libjpeg.a to a binary from libjpeg-turbo and this warning disappeared. This binary however doesn't include a slice for arm64.

After fixing the warning for libjpeg, the same warning appeared for libtiff:

```
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in __TIFFMultiply32 from /Users/user/Library/Developer/Xcode/DerivedData/Project/Build/Products/Debug-iphoneos/libcocos2dx iOS.a(tif_aux.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
```

Replacing tiff/prebuilt/ios/libtiff.a also fixed the warning. There were no more warnings concerning PIE and now running "otool -hv" on the .app shows the PIE flag (it didn't before).

I don't know how libjpeg and libtiff are being compiled but it might be worth looking into it. Thanks.

**Comment by Zambiorix** [comment]
where did you get the libtiff.a library to replace the one in "tiff/prebuilt/ios/" ?

thanks!

**Comment by pyrosphere** [comment]
I don't remember, sorry - I vaguely remember trying to compile it but not sure if I was successful or if I ended up grabbing a binary online.

**Comment by Zambiorix** [comment]
For those interested, grab the libs package from Imagemagick:
http://www.imagemagick.org/download/iOS/

And replace for cocos2d-x/external/jpeg and cocos2d-x/external/tiff both the include files and the prebuilt libs for ios with the ones from Imagemagick. Clean and rebuild and all should be fine. "otool -hv" shows PIE flag.

Don't forget, if you run "download-deps.py", those files are overwritten again ...

**Comment by pyrosphere** [comment]
Those are great, thanks! They include armv64 and starting on February 1st 2015, new apps will require 64-bit support: https://developer.apple.com/news/?id=10202014a

```
lipo -info libtiff.a 
Architectures in the fat file: libtiff.a are: armv7 armv7s i386 x86_64 arm64 

lipo -info libpng.a 
Architectures in the fat file: libpng.a are: armv7 armv7s i386 x86_64 arm64
```

Edit: Actually I just tried them out in my project (which is using cocos2d-x 3.2) and I get the following error:

```
cocos2d: jpeg error: JPEG parameter struct mismatch: library thinks size is 488, caller expects 452
```

**Comment by Zambiorix** [comment]
did you copy all the headers ? (i think there is one additional header for jpeg)

**Comment by pyrosphere** [comment]
I didn't, might have been that. Thanks.

**Comment by Zambiorix** [comment]
no worries

all works in my projects

**Comment by Zambiorix** [comment]
I thought non-PIE apps are not allowed on the appstore? I wonder why nobody of the regular cocos2d-x maintainers have noticed this problem. 

I just moved to the latest 3.3rc0 and the problem still persists

**Comment by pyrosphere** [comment]
Apple prefers PIE apps, but you can still submit a non-PIE app and it will probably be accepted - they might give you a warning about that though.

**Comment by Zambiorix** [comment]
Noticed the warning a long time ago, didn't submit a non-pie app for a while. Thought they would have forced it by now...

**Comment by Pstoppani** [comment]
I'm on cocos2d-x 3.3 and still get this warning.  I tried the suggest libraries above and this did not fix it.

**Comment by zilongshanren** [comment]
@Pstoppani 
Hi, how could I reproduce this warning? Should I upload the app to AppStore or just compile it ?

**Comment by Pstoppani** [comment]
I created a simple project in 3.3 and ran it on my iPhone.  

Pete

**Comment by Leandros** [comment]
Still persists in cocos2d-x 3.4.

```
PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in _jinit_arith_decoder from /Applications/Cocos/frameworks/cocos2d-x-3.4rc1/prebuilt/ios/libcocos2d iOS.a(jdarith.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
```

**Comment by zilongshanren** [comment]
@minggo 
I found in our cpp-test project, the *Generate Position-Dependent Code" is disabled. Should we turn it on?

**Comment by minggo** [comment]
Yes please if it doesn't have any side-effect.

**Comment by stevetranby** [comment]
Shouldn't cpp-test be setup for best practice? Not working around this issue by setting it to YES, but rather keeping it as NO and fixing the issue with the core and 3rd party libraries?

**Comment by minggo** [comment]
@stevetranby 
Yep, we should fix it in correct way.
Did you mean it is caused by the libraries?
If so, i think we should re-build  them.

**Comment by zilongshanren** [comment]
@stevetranby  I will consider to compile all the 3rd party libraries with PIE flag. But now it doesn't has such a high priority.

**Comment by jonnyijapan** [comment]
Still seeing this in Cocos2dX 3.5. What do I do??

**Comment by zilongshanren** [comment]
@jonnyijapan  Fixed at https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/137
