### ISSUE TITLE
libuv prebuilt for windows is a debug version

### ISSUE THREAD

**Issue by juan-medina** [cocos2d/cocos2d-x-3rd-party-libs-bin#353]
The prebuild libuv binary is a debug version, this force to any windows application created to need to have the debug runtime.

<img width="654" alt="lib_uv" src="https://user-images.githubusercontent.com/485083/57913614-e127aa00-7884-11e9-9f75-d14b5fad29e2.png">

I was trying to see if I could do a pull request to fix it but is not clear how this works, I understand there is a project to build the dependencies but not sure if that is the case for libuv or we just add the binary.

I can add the binary but which version of libuv we are using so I do the correct one?

Thanks

**Comment by minggo** [comment]
Did you mean `uv/prebuilt/win32/uv.dll`?

**Comment by juan-medina** [comment]
> Did you mean `uv/prebuilt/win32/uv.dll`?

Yes, both the win32 and win10

I've create a PR for this
